[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = ""
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "14"

[build]
  publish = "build/"
  command = "yarn build"

[[headers]]
  for = "/static/*"

  [headers.values]
    cache-control = "max-age=31536000"