import React, { useEffect, useState } from "react";
import { nanoid } from "nanoid";
import logo from "img/math-app.png";

function PrintMode({ game, printAmountQuestions }: { game: import("../util/modes").Mode; printAmountQuestions: number }) {
  enum ProblemType {
    MC = "MultipleChoice",
    Text = "Text",
  }

  const [questions, setQuestions] = useState([]);

  useEffect(() => {
    if (game && questions.length === 0) {
      console.log("update questions");
      Promise.all(
        Array(printAmountQuestions)
          .fill(null)
          .map(async () => await game.gen())
      ).then((v) => setQuestions(v));
    }
  }, [game, printAmountQuestions, questions]);

  return (
    <div className="print-only">
      {game && (
        <>
          <nav className="navbar navbar-expand-sm navbar-light">
            <div className="container-md">
              <div className="text-center w-100">
                <img src={logo.src} alt="" style={{ height: "2rem" }} className="me-2" />
                <span className="navbar-brand me-0 me-sm-3" style={{ verticalAlign: "middle" }}>
                  {game.name} - Math Challenges
                </span>
              </div>
            </div>
          </nav>
          <hr style={{ borderTop: "1px solid var(--bs-gray-800)" }} />
          <div style={{ columnGap: "2rem", columnCount: 2, columnRule: "1px solid rgb(220, 220, 220)" }}>
            {questions.map((v, i) => (
              <div key={nanoid(6)} style={{ breakInside: "avoid" }}>
                <div style={{ textAlign: "center", fontSize: "1.25em", fontWeight: "bold" }}>{i + 1}.</div>
                <div style={{ textAlign: "center" }}>{v.q}</div>
                <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "center" }}>
                  {v.type === ProblemType.Text ? (
                    <div className="input-group">
                      <input className="ms-2 form-control" type="text" style={{ width: "16px" }} />
                    </div>
                  ) : (
                    <p className="text-center mb-0">
                      {v.opts.map((v, i) => (
                        <span key={nanoid(6)}>
                          <b>{["A", "B", "C", "D", "E", "F", "G", "H"][i]}.</b> {v.text}&emsp;
                        </span>
                      ))}
                    </p>
                  )}
                </div>
                <hr style={{ borderTop: "1px solid var(--bs-gray-800)" }} />
              </div>
            ))}
          </div>

          <footer>This worksheet was generated by math.shivam.pro. If you are a student, tell your teacher that you love this worksheet. If you are a teacher, share this with other teachers!</footer>
        </>
      )}
    </div>
  );
}

export default PrintMode;
